version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: docker-next
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
